[package]
name = "primerpincer"
version = "0.3.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.100"
bio = "3.0.0"
clap = { version = "4.5.51", features = ["derive"] }
flate2 = "1.1.5"
niffler = "2.5"
once_cell = "1.19"
paraseq = { version = "0.4.3", default-features = false, features = ["anyhow", "niffler"] }
sassy = "0.1.6"


[dev-dependencies]
tempfile = "3.23.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

