[package]
name = "primerpincer"
version = "0.5.0"
edition = "2024"
license = "MIT"
authors = ["Maurice Barrett <mauricepatrickbarrett@gmail.com>"]
description = "A CLI primer trimming tool for long-read sequencing data"
repository = "https://github.com/mauricebarrett/primerpincer"
homepage = "https://github.com/mauricebarrett/primerpincer"
documentation = "https://github.com/mauricebarrett/primerpincer"
keywords = ["bioinformatics", "primers", "sequencing", "fastq", "microbiome"]
categories = ["command-line-utilities", "science"]
readme = "README.md"
exclude = [
    "example_data/",
    "docs/",
    "setup.sh",
    "pixi.toml",
    "pixi.lock",
    ".pixi",
    "package.json",
    ".github/",
]


[dependencies]
anyhow = "1.0.100"
bio = "3.0.0"
clap = { version = "4.5.51", features = ["derive"] }
flate2 = "1.1.5"
niffler = "2.5"
once_cell = "1.19"
paraseq = { version = "0.4.3", default-features = false, features = ["anyhow", "niffler"] }
sassy = { version = "0.1.6", features = ["scalar"] }


[dev-dependencies]
tempfile = "3.23.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

