name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR commits
        uses: cocogitto/cocogitto-action@v3
        with:
          check-latest-tag-only: true  # Only check commits since last tag
